apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-demo-driver-pvc-01
  namespace: csi-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: demo-csi