kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: demo-csi
provisioner: csi.demo.plugin.com
parameters:
  ugi_config: "gpu,gpu"
  confPath: "/tmp/conf"
  stagePath: "/search/odin"
  fuse.debug: "true"
